// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package top.lllyl2012.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.lllyl2012.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .top.lllyl2012.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<top.lllyl2012.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .top.lllyl2012.proto.StudentResponse studentResponse = 1;</code>
   */
  top.lllyl2012.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .top.lllyl2012.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .top.lllyl2012.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends top.lllyl2012.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .top.lllyl2012.proto.StudentResponse studentResponse = 1;</code>
   */
  top.lllyl2012.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
